### PR TITLE
return monthly principal and interest amounts

### PR DESCRIPTION
**Pull request by cfarm**
## Added
* expose monthly principal + monthly interest amounts for use in the [monthly amounts breakdown](https://github.com/cfpb/owning-a-home/commit/5ae23cd0d5486e69a8d4cd8882f0ed5e242756cd#diff-87728865f2f2c8cae97a1eb94d91a574)

## Review
* @virginiacc 
* @contolini

### CODE REVIEW

**Comment by contolini** [comment]
Easy peasy. Be sure to update the readme and tests.

**Comment by cfarm** [comment]
@mthibos can you review this math? :1234: :tada: 

* A borrower with a 30 year, $180,000 loan with a 4.25% interest rate will pay $885.49 monthly
* A borrower with a 30 year, $180,000 loan with a 4.25% interest rate will pay $579.98 in interest monthly
* A borrower with a 30 year, $180,000 loan with a 4.25% interest rate will pay $305.51 in principal monthly

**Comment by jimmynotjim** [comment]
Very cool. Having manually done this before I would have loved to have had this library.

**Comment by mthibos** [comment]
@cfarm 

The $885.49 number is correct.

I'm not sure how you calculated the separate interest and principal numbers, but they're not correct -- in fact, there are no "correct" values for these items.  It is a fundamental nature of mortgages that the precise amount going to interest vs principal changes every single payment.  

So, we don't want to expose those separate numbers in the tool or to anyone who might be borrowing this module for their own coding purposes.  Instead, we want to report just a single number -- "principal and interest".

Let me know if that doesn't make sense.

**Comment by cfarm** [comment]
Ah, so principal + interest is actually what was already being calculated as the monthly payment value here. 

So then monthly payment for the design's purposes is this principal+interest value plus the mortgage insurance, property taxes and insurance, and hoa dues, correct?

**Comment by mthibos** [comment]
@cfarm  That's correct.

**Pull request closed without merging**
