### PR TITLE
Added support for equal principal payment

### PR DESCRIPTION
**Pull request by yonatann**

### CODE REVIEW

**Comment by contolini** [comment]
Hey @yonatann! Thanks so much for this feature. When you have moment can you add a few [tests](https://github.com/cfpb/amortize/blob/master/test/test.js) that include the new config options?

**Comment by yonatann** [comment]
Sure, I've added tests to the test.js file.

I also added another option: 'paritalMonthOffset'
You can use this option to offset the payment day of the month e.g.
If you take the loan on the 15th (of a 30 day month) and you would like the payments to be made on the 1st of each month then you set this option to 0.5

**Comment by avantassel** [comment]
@yonatann I added extra principal payment a few months ago, I'm using it in https://github.com/avantassel/finterest

**Comment by contolini** [comment]
Thanks @yonatann -- published as part of v1.0.0!

**Pull request merged**
